### ISSUE TITLE
Connection timeouts cause crash

### ISSUE THREAD

**Issue by cyberbit** [Colonial-Dev/satpaper#10]
While running satpaper, if the connection experiences a momentary outage (either on client or SLIDER end) while tiles are being collected, the program loop crashes. Here's an excerpt of the log when that occurs:

![image](https://github.com/Colonial-Dev/satpaper/assets/7350183/0c826e01-e8ea-4794-bc33-28c383ebb25c)

The exact message and segment of code varies depending on what stage of the loop is running. Maybe a gated "retry x times" flag with exponential backoff would be good here? If retrying each tile isn't feasible, then maybe logging the error was caught and waiting for next schedule to retry. I figured failing outright probably isn't intended.

**Comment by Colonial-Dev** [comment]
I think it makes the most sense to just catch/log the error and wait until the next go round. The delay is negligible (sixty seconds, assuming the outage is momentary.)

> I figured failing outright probably isn't intended.

Yeeeah, I'm a little too used to "just HCF and let `systemd` restart the thing."

**Comment by cyberbit** [comment]
> let systemd restart the thing

Ha, yeah this was my plan for the Docker container regardless. Long live `systemd`!

**Comment by Colonial-Dev** [comment]
(Forgot to trap errors from another request function - sorry if you already built the previous commit!)
