### ISSUE TITLE
Trouble with running the docker container

### ISSUE THREAD

**Issue by NomLom** [Colonial-Dev/satpaper#19]
Hi there Colonial-Dev,

I'm having trouble running the docker container.

From the console, I cd into the docker directory.

I use 'docker-compose up -d'

It has errors compiling fimg v0.4.20 (see log below).   I've been trying to edit the files to repair the error based on the log but I don't know rust and nothing is jumping out at me.

╭─x@x in repo: satpaper/docker on  master [!] via  desktop-linux took 25ms
[🔴] × docker-compose up
[+] Building 32.1s (20/22)                                                               docker:desktop-linux
=> [satpaper internal] load build definition from Dockerfile                                            0.0s
=> => transferring dockerfile: 651B                                                                     0.0s
=> [satpaper internal] load .dockerignore                                                               0.0s
=> => transferring context: 2B                                                                          0.0s
=> [satpaper internal] load metadata for docker.io/library/alpine:latest                                1.2s
=> [satpaper internal] load metadata for docker.io/library/rust:alpine                                  1.5s
=> [satpaper auth] library/alpine:pull token for registry-1.docker.io                                   0.0s
=> [satpaper auth] library/rust:pull token for registry-1.docker.io                                     0.0s
=> [satpaper base 1/8] FROM docker.io/library/rust:alpine@sha256:2e505c3e2863b0a4627219ccd538aeef3de5f  0.0s
=> [satpaper production 1/5] FROM docker.io/library/alpine@sha256:51b67269f354137895d43f3b3d810bfacd39  0.0s
=> [satpaper internal] load build context                                                               0.0s
=> => transferring context: 326B                                                                        0.0s
=> CACHED [satpaper base 2/8] WORKDIR /code                                                             0.0s
=> CACHED [satpaper base 3/8] COPY Cargo.toml .                                                         0.0s
=> CACHED [satpaper base 4/8] COPY Cargo.lock .                                                         0.0s
=> CACHED [satpaper base 5/8] COPY rust-toolchain.toml .                                                0.0s
=> CACHED [satpaper base 6/8] COPY src/ src/                                                            0.0s
=> CACHED [satpaper base 7/8] RUN apk update && apk add g++ zlib zlib-dev                               0.0s
=> CACHED [satpaper base 8/8] RUN cargo fetch --locked                                                  0.0s
=> CACHED [satpaper production 2/5] WORKDIR /home/rust/                                                 0.0s
=> CACHED [satpaper production 3/5] RUN apk update && apk add supervisor                                0.0s
=> CACHED [satpaper production 4/5] COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.co  0.0s
=> ERROR [satpaper test 1/1] RUN cargo test --release                                                  30.4s
------
> [satpaper test 1/1] RUN cargo test --release:
0.304    Compiling autocfg v1.1.0
0.304    Compiling cfg-if v1.0.0
0.304    Compiling libc v0.2.149
0.304    Compiling proc-macro2 v1.0.69
0.304    Compiling unicode-ident v1.0.12
0.304    Compiling simd-adler32 v0.3.7
0.304    Compiling crc32fast v1.3.2
0.304    Compiling adler v1.0.2
0.305    Compiling crossbeam-utils v0.8.16
0.305    Compiling tinyvec_macros v0.1.1
0.305    Compiling untrusted v0.9.0
0.305    Compiling spin v0.9.8
0.306    Compiling scopeguard v1.2.0
0.306    Compiling utf8parse v0.2.1
0.306    Compiling rustix v0.38.21
0.308    Compiling memchr v2.6.4
0.333    Compiling tinyvec v1.6.0
0.337    Compiling regex-syntax v0.8.2
0.377    Compiling anstyle-parse v0.2.2
0.380    Compiling percent-encoding v2.3.0
0.388    Compiling anstyle v1.0.4
0.403    Compiling rayon-core v1.12.0
0.417    Compiling colorchoice v1.0.0
0.438    Compiling weezl v0.1.7
0.475    Compiling miniz_oxide v0.7.1
0.549    Compiling fdeflate v0.3.0
0.607    Compiling serde v1.0.190
0.646    Compiling rustls v0.21.8
0.649    Compiling bitflags v2.4.1
0.793    Compiling bitflags v1.3.2
0.808    Compiling anstyle-query v1.0.0
0.825    Compiling memoffset v0.9.0
0.827    Compiling num-traits v0.2.17
0.852    Compiling crossbeam-epoch v0.9.15
0.865    Compiling num-integer v0.1.45
0.891    Compiling num-rational v0.4.1
0.981    Compiling unicode-bidi v0.3.13
1.039    Compiling linux-raw-sys v0.4.10
1.064    Compiling log v0.4.20
1.201    Compiling aho-corasick v1.1.2
1.324    Compiling quote v1.0.33
1.389    Compiling flate2 v1.0.28
1.556    Compiling crossbeam-deque v0.8.3
1.761    Compiling cc v1.0.83
1.793    Compiling getrandom v0.2.10
1.801    Compiling syn v2.0.38
1.829    Compiling unicode-normalization v0.1.22
1.831    Compiling anstream v0.6.4
1.835    Compiling form_urlencoded v1.2.0
1.841    Compiling jpeg-decoder v0.3.0
1.866    Compiling color_quant v1.1.0
2.012    Compiling strsim v0.10.0
2.092    Compiling png v0.17.10
2.151    Compiling umath v0.0.7
2.223    Compiling anyhow v1.0.75
2.297    Compiling serde_json v1.0.107
2.386    Compiling bytemuck v1.14.0
2.390    Compiling heck v0.4.1
2.471    Compiling clap_lex v0.6.0
2.495    Compiling vecto v0.1.1
2.574    Compiling gif v0.12.0
2.651    Compiling idna v0.4.0
2.664    Compiling clap_builder v4.4.7
2.766    Compiling qoi v0.4.1
2.888    Compiling humantime v2.1.0
3.119    Compiling regex-automata v0.4.3
3.197    Compiling is-terminal v0.4.9
3.262    Compiling tiff v0.9.0
3.313    Compiling webpki-roots v0.25.2
3.350    Compiling either v1.9.0
3.382    Compiling termcolor v1.3.0
3.533    Compiling url v2.4.1
3.806    Compiling mattr v0.0.2
3.873    Compiling base64 v0.21.5
4.003    Compiling ring v0.17.5
4.025    Compiling itoa v1.0.9
4.166    Compiling byteorder v1.5.0
4.443    Compiling once_cell v1.18.0
4.546    Compiling fer v0.1.1
4.566    Compiling ryu v1.0.15
4.721    Compiling rayon v1.8.0
4.932    Compiling image v0.24.7
6.951    Compiling fimg v0.4.20
6.998 error[E0432]: unresolved imports `std::simd::SimdInt`, `std::simd::SimdPartialOrd`
6.998  --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fimg-0.4.20/src/overlay.rs:5:37
6.998   |
6.998 5 | use std::simd::{simd_swizzle, Simd, SimdInt, SimdPartialOrd};
6.998   |                                     ^^^^^^^  ^^^^^^^^^^^^^^ no `SimdPartialOrd` in `simd`
6.998   |                                     |
6.998   |                                     no `SimdInt` in `simd`
6.998   |
6.998   = help: consider importing one of these items instead:
6.998           core::simd::prelude::SimdInt
6.998           std::simd::prelude::SimdInt
6.998   = help: consider importing one of these items instead:
6.998           core::simd::prelude::SimdPartialOrd
6.998           std::simd::prelude::SimdPartialOrd
6.998
7.074    Compiling serde_derive v1.0.190
7.074    Compiling clap_derive v4.4.7
7.142 error[E0599]: no method named `simd_ge` found for struct `Simd` in the current scope
7.142   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/fimg-0.4.20/src/overlay.rs:69:29
7.142    |
7.142 69 |         let threshold = new.simd_ge(Simd::splat(128)).to_int().cast::<u8>();
7.143    |                             ^^^^^^^ method not found in `Simd<u8, 16>`
7.143   --> /rustc/88189a71e4e4376eea82ac61db6a539612eb200a/library/core/src/../../portable-simd/crates/core_simd/src/simd/cmp/ord.rs:24:8
7.143    |
7.143    = note: the method is available for `Simd<u8, 16>` here
7.143    |
7.143    = help: items from traits can only be used if the trait is in scope
7.143 help: the following trait is implemented but not in scope; perhaps add a `use` for it:
7.143    |
7.143 2  + use std::simd::cmp::SimdPartialOrd;
7.143    |
7.143
7.218    Compiling regex v1.10.2
7.224 Some errors have detailed explanations: E0432, E0599.
7.224 For more information about an error, try `rustc --explain E0432`.
7.233 error: could not compile `fimg` (lib) due to 2 previous errors
7.233 warning: build failed, waiting for other jobs to finish...
------
failed to solve: process "/bin/sh -c cargo test --release" did not complete successfully: exit code: 101

**Comment by NomLom** [comment]
I'm pretty new to Garuda Linux, I wanted to docker so I can keep my system clean, so Rust is not on the host.

**Comment by Colonial-Dev** [comment]
Ah, the joys of riding the nightly release train. Looks like some stuff got swapped around and caused the old `fimg` version to break - try cloning the latest update to `master`, it should work now.
