### ISSUE TITLE
Support generating image only?

### ISSUE THREAD

**Issue by cyberbit** [Colonial-Dev/satpaper#8]
Is building in support to generate an image only something that is out of scope for this project? I'm considering building out a Docker container that builds from source and outputs a file to a network share so I can reuse the generated image across machines.

**Comment by Colonial-Dev** [comment]
There's actually already support for this - I just that the only way to discover it is through the command line help. (Funnily enough, I had *just* fixed a bug with it when I got the notification for this issue.)

What you're looking for is the `--once`/`SATPAPER_ONCE` argument:

```
-o, --once

Whether or not to only run once.

By default, Satpaper is designed to run in the background - it stays resident once launched and peroidically 
attempts to update your wallpaper.

With --once set, Satpaper will instead generate one wallpaper and terminate, without affecting your existing 
wallpaper or staying resident.

This is ideal if you want to use Satpaper as a simple wallpaper generator or as part of a 
larger script/program.

[env: SATPAPER_ONCE=]
```
Practically, you would run it like this:
```
satpaper --satellite goes-east -x 2560 -y 1440 -d 95 -t <SOME_TARGET_PATH> --once
```
... Which should generate an image, save it to `<SOME_TARGET_PATH>`, and then terminate without attempting to futz with the desktop environment.

**Comment by cyberbit** [comment]
Ah, that makes perfect sense. Thanks!

**Comment by Colonial-Dev** [comment]
No problem! And thanks for filing this issue - I totally forgot to document these options in the README.

**Comment by cyberbit** [comment]
Success 😎 
![image](https://github.com/Colonial-Dev/satpaper/assets/7350183/b4579871-c747-4bcd-a3f2-2ba71ea555d4)
